---
# tasks file for ansible-mas

- name: Ensure mas-cli is installed
  homebrew:
    name: mas
    state: present
  when: mas_apps|count > 0

- name: Install App Store Apps
  community.general.mas:
    id: "{{ item.id|default(item) }}"
    state: present
  loop: "{{ mas_apps }}"
  when: mas_apps|default([])|count > 0
